# Generated by Django 3.2.7 on 2022-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('start', models.CharField(max_length=255, null=True)),
                ('end', models.CharField(max_length=255, null=True)),
                ('participants', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
